### ISSUE TITLE
Bump going from 1.0.9 to 1.0.100

### ISSUE THREAD

**Issue by ghost** [treeder/dockers#1]
Hi,

Currently using your image to bump my released docker images for a node application.
I'm trying to release version 1.0.10 but the container is actually writing 1.0.100 into the VERSION file instead of 1.0.10.

Logs are here - 
```docker run --rm -v /home/lciadm100/jenkins/workspace/spinnaker_testing:/app -w /app treeder/bump patch
Current version: 1.0.9
New version: 1.0.10
cat VERSION
export VERSION=1.0.100
VERSION=1.0.100
```

Commands used are here - 
```
docker run --rm -v $PWD:/app -w /app treeder/bump patch
export VERSION=`cat VERSION`
```

Have you come across this before?

Any help would be much appreciated.

Thanks,
Sean

**Comment by treeder** [comment]
Looking at it...

**Comment by treeder** [comment]
Try it now, let me know if it works.

**Comment by jimmycasey** [comment]
Current version: 0.0.9
New version: 0.0.10
version: 0.0.10

Works perfect, thanks.
