### ISSUE TITLE
Slice Bounds out of Range error going from version 0.0.9 to 0.0.10

### ISSUE THREAD

**Issue by dongreenmedl** [treeder/dockers#3]
When using this image, I can into the following error when my patch version was bumping beyond a single digit value (0.0.9 to 0.0.10).

```bash
Old version: 0.0.9
New version: 0.0.10
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.bump(0xc42006e2c0, 0x0, 0x0)
        /go/src/github.com/treeder/dockers/bump/bump.go:92 +0xa3d
github.com/treeder/dockers/bump/vendor/github.com/urfave/cli.HandleAction(0x5539c0, 0x58cec0, 0xc42006e2c0, 0x0, 0x0)
        /go/src/github.com/treeder/dockers/bump/vendor/github.com/urfave/cli/app.go:490 +0xd2
github.com/treeder/dockers/bump/vendor/github.com/urfave/cli.(*App).Run(0xc4200584e0, 0xc42000a060, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/treeder/dockers/bump/vendor/github.com/urfave/cli/app.go:264 +0x635
main.main()
        /go/src/github.com/treeder/dockers/bump/bump.go:35 +0x30c
```

It appears this issue is caused by the growing character count since manually modifying the referenced `VERSION` file to 0.0.10 and letting the bump run works perfectly for transitioning from 0.0.10 to 0.0.11.

**Comment by treeder** [comment]
Can you be sure you're using >= `treeder/bump:1.2.3` ?  https://hub.docker.com/r/treeder/bump/tags/

I believe this was fixed recently so pleasetry it with that 1.2.3 tag and let me know if it works.

**Comment by dongreenmedl** [comment]
I tested using the 1.2.3 tag and it works as expected. Evidently enough, I back tested using older versions and could not reproduce the issue I found above. I am not really sure why it doesn't happen anymore even with older images, but id say this is no longer an issue. I apologize for the false alarm and thank your for a lightweight and comprehensive image for managing semantic versioning ;D.

**Comment by treeder** [comment]
Good to hear and glad you like it. :)
